[workspace]
members = [
    "backend/canisters/bucket/api",
    "backend/canisters/bucket/impl",
    "backend/canisters/index/api",
    "backend/canisters/index/impl",
    "backend/libraries/candid_gen",
    "backend/libraries/env",
    "backend/libraries/types",
    "backend/libraries/utils"
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
