[workspace]
members = [
    "backend/canister_installer",
    "backend/canisters/bucket/api",
    "backend/canisters/bucket/c2c_client",
    "backend/canisters/bucket/impl",
    "backend/canisters/index/api",
    "backend/canisters/index/c2c_client",
    "backend/canisters/index/impl",
    "backend/libraries/candid_gen",
    "backend/libraries/canister_api_macros",
    "backend/libraries/canister_client",
    "backend/libraries/canister_client_macros",
    "backend/libraries/canister_logger",
    "backend/libraries/http_request",
    "backend/libraries/serializer",
    "backend/libraries/types",
    "backend/libraries/utils"
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
