[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.7"
generic-array = "0.14.4"
ic-cdk = { git = "https://github.com/hpeebles/cdk-rs", rev = "827d553181aaac61cf6209aa0654baf19b1dbef4" }
rand = "0.7.3"
serde = "1.0.126"
serde_bytes = "0.11.5"
sha3 = "0.9.1"
tracing = "0.1.29"
types = { path = "../types" }