[package]
name = "canister_client"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bucket_canister = { path = "../../canisters/bucket/api" }
candid = "0.7.7"
canister_client_macros = { path = "../canister_client_macros", features = ["ingress"] }
dirs = "3.0.2"
garcon = "0.2.3"
ic-agent = "0.7.0"
ic-utils = "0.5.0"
index_canister = { path = "../../canisters/index/api" }
index_canister_client = { path = "../../canisters/index/client" }
serde = "1.0.126"
types = { path = "../types" }
