on:
  pull_request:
    branches:
      - main

name: Validate candid files

jobs:
  candid_syntax:
    name: validate candid syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: install didc 0.7.10
        uses: supplypike/setup-bin@v1
        with:
          uri: https://github.com/dfinity/candid/releases/download/2022-01-06/didc-linux64
          name: didc
          version: 0.7.10
      - name: run validate-candid-syntax.sh
        run: ./validate-candid-syntax.sh
        shell: bash

  candid_matches_rust:
    name: validate candid matches rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: install didc 0.7.10
        uses: supplypike/setup-bin@v1
        with:
          uri: https://github.com/dfinity/candid/releases/download/2022-01-06/didc-linux64
          name: didc
          version: 0.7.10
      - name: run validate-candid-matches-rust.sh
        run: ./validate-candid-matches-rust.sh
        shell: bash
